import { Navbar } from '@/components/layout/navbar'
import { Footer } from '@/components/layout/footer'
import { ScanLine, Target, Shield, Users } from 'lucide-react'

export default function AboutPage() {
  return (
    <>
      <Navbar />
      <main className="pt-16">
        <section className="py-20 bg-slate-50">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="text-center mb-12">
              <div className="inline-flex items-center gap-2 bg-blue-50 text-blue-700 border border-blue-100 rounded-full px-4 py-1.5 text-sm font-medium mb-4">
                <ScanLine className="w-4 h-4" />
                SIH 2026 — PSC26034
              </div>
              <h1 className="text-4xl font-bold text-slate-900 mb-4">About LabelCheck</h1>
              <p className="text-lg text-slate-500 max-w-2xl mx-auto">
                An AI-powered compliance checking tool built for the Smart India Hackathon 2026.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-12">
              {[
                { icon: Target, title: 'Our Mission', desc: 'To make Legal Metrology compliance verification fast, accessible and accurate for businesses, consumers and enforcement authorities.' },
                { icon: Shield, title: 'The Problem', desc: 'Millions of packaged products in India may have missing or non-compliant declarations. Manual verification is slow and error-prone.' },
                { icon: Users, title: 'Who It Helps', desc: 'Manufacturers, retailers, consumer protection bodies, enforcement inspectors, and aware consumers.' },
              ].map(item => (
                <div key={item.title} className="bg-white rounded-2xl p-6 border border-slate-200 shadow-sm">
                  <div className="w-10 h-10 bg-blue-50 rounded-xl flex items-center justify-center mb-4">
                    <item.icon className="w-5 h-5 text-blue-600" />
                  </div>
                  <h3 className="font-semibold text-slate-900 mb-2">{item.title}</h3>
                  <p className="text-sm text-slate-500 leading-relaxed">{item.desc}</p>
                </div>
              ))}
            </div>

            <div className="bg-white rounded-2xl border border-slate-200 p-8 shadow-sm">
              <h2 className="text-xl font-bold text-slate-900 mb-4">Important Disclaimer</h2>
              <div className="prose prose-sm text-slate-600 space-y-3">
                <p>LabelCheck is a <strong>demonstration tool</strong> built for the Smart India Hackathon 2026 (Problem Statement PSC26034). It is not an official government tool and does not carry any legal authority.</p>
                <p>Results generated by LabelCheck are <strong>indicative only</strong> and should not be used as legal evidence or as the sole basis for compliance decisions.</p>
                <p>The analysis is based on visible information in the uploaded image and may not capture all declarations present on the physical product. Always verify compliance against the actual product and the applicable Legal Metrology rules.</p>
                <p>LabelCheck does not claim any official government affiliation or endorsement.</p>
              </div>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  )
}
